version: "3.9"
services:
 base-project-api-dev:
  image: renzodotexe/base-project-api-dev
  ports:
    - "8000:8000"
  volumes:
    - sqlite_useritems_volume:/code/sqlitedb

volumes:
  sqlite_useritems_volume: